# $File: //ASP/opa/acc/eqc/pla/testo/trunk/testoSup/Db/Makefile $
# $Revision: #1 $
# $DateTime: 2022/08/17 17:06:12 $
# Last checked in by: $Author: starritt $
#

TOP=../..
include $(TOP)/configure/CONFIG
include $(PYDEVSUP)/configure/CONFIG_PY
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
PY += mokuEPICS.py

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
include $(PYDEVSUP)/configure/RULES_PY
#----------------------------------------
#  ADD RULES AFTER THIS LINE

# end
