# $File: //ASP/opa/acc/eqc/pla/testo/trunk/testoSup/Db/Makefile $
# $Revision: #1 $
# $DateTime: 2022/08/17 17:06:12 $
# Last checked in by: $Author: starritt $
#

TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
#
DB += mokuSpecAn.template
DB += mokuSpecAnChan.template

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

# end